import {
  Activity,
  Airplay,
  Archive,
  Backpack,
  Bell,
  Blocks,
  Book,
  Bot,
  Box,
  Briefcase,
  Brush,
  Bug,
  Building,
  Calendar,
  Camera,
  Clock,
  Cloud,
  Code,
  Coffee,
  Command,
  Compass,
  Cpu,
  CreditCard,
  Database,
  Download,
  Droplet,
  Eye,
  Feather,
  Film,
  Flag,
  Flame,
  Folder,
  Gauge,
  Gift,
  Globe,
  Grid,
  Hammer,
  Headphones,
  Heart,
  Image,
  Inbox,
  Key,
  Keyboard,
  Laptop,
  Layers,
  Library,
  Lightbulb,
  Link,
  List,
  Lock,
  Mail,
  Map,
  MapPin,
  Megaphone,
  Mic,
  Monitor,
  Moon,
  Mountain,
  Music,
  Navigation,
  Newspaper,
  Notebook,
  Package,
  Palette,
  Paperclip,
  PieChart,
  Play,
  Plug,
  Podcast,
  Power,
  Printer,
  Puzzle,
  Radio,
  Receipt,
  Rocket,
  Rss,
  Ruler,
  Save,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  Share,
  Shield,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Speaker,
  Star,
  Store,
  Sun,
  Tag,
  Target,
  Terminal,
  Thermometer,
  Timer,
  Trash,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  Type,
  Umbrella,
  Upload,
  User,
  Users,
  Video,
  Wallet,
  Watch,
  Wifi,
  Wind,
  Wrench,
  Zap,
  ZoomIn,
  type LucideIcon,
} from "lucide-react";

/** 显式登记而不是全量引入：只有这里列出的图标会进包 */
export const lucideRegistry = {
  activity: Activity,
  airplay: Airplay,
  archive: Archive,
  backpack: Backpack,
  bell: Bell,
  blocks: Blocks,
  book: Book,
  bot: Bot,
  box: Box,
  briefcase: Briefcase,
  brush: Brush,
  bug: Bug,
  building: Building,
  calendar: Calendar,
  camera: Camera,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  coffee: Coffee,
  command: Command,
  compass: Compass,
  cpu: Cpu,
  "credit-card": CreditCard,
  database: Database,
  download: Download,
  droplet: Droplet,
  eye: Eye,
  feather: Feather,
  film: Film,
  flag: Flag,
  flame: Flame,
  folder: Folder,
  gauge: Gauge,
  gift: Gift,
  globe: Globe,
  grid: Grid,
  hammer: Hammer,
  headphones: Headphones,
  heart: Heart,
  image: Image,
  inbox: Inbox,
  key: Key,
  keyboard: Keyboard,
  laptop: Laptop,
  layers: Layers,
  library: Library,
  lightbulb: Lightbulb,
  link: Link,
  list: List,
  lock: Lock,
  mail: Mail,
  map: Map,
  "map-pin": MapPin,
  megaphone: Megaphone,
  mic: Mic,
  monitor: Monitor,
  moon: Moon,
  mountain: Mountain,
  music: Music,
  navigation: Navigation,
  newspaper: Newspaper,
  notebook: Notebook,
  package: Package,
  palette: Palette,
  paperclip: Paperclip,
  "pie-chart": PieChart,
  play: Play,
  plug: Plug,
  podcast: Podcast,
  power: Power,
  printer: Printer,
  puzzle: Puzzle,
  radio: Radio,
  receipt: Receipt,
  rocket: Rocket,
  rss: Rss,
  ruler: Ruler,
  save: Save,
  scissors: Scissors,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  share: Share,
  shield: Shield,
  "shopping-bag": ShoppingBag,
  smartphone: Smartphone,
  sparkles: Sparkles,
  speaker: Speaker,
  star: Star,
  store: Store,
  sun: Sun,
  tag: Tag,
  target: Target,
  terminal: Terminal,
  thermometer: Thermometer,
  timer: Timer,
  trash: Trash,
  "trending-up": TrendingUp,
  trophy: Trophy,
  truck: Truck,
  tv: Tv,
  type: Type,
  umbrella: Umbrella,
  upload: Upload,
  user: User,
  users: Users,
  video: Video,
  wallet: Wallet,
  watch: Watch,
  wifi: Wifi,
  wind: Wind,
  wrench: Wrench,
  zap: Zap,
  "zoom-in": ZoomIn,
} satisfies Record<string, LucideIcon>;

export type LucideName = keyof typeof lucideRegistry;

export const lucideNames = Object.keys(lucideRegistry) as LucideName[];

export function getLucideIcon(name: string | null | undefined): LucideIcon | null {
  if (!name) return null;
  return lucideRegistry[name as LucideName] ?? null;
}
